Adding support for NAT in Apigee
GoogleCloudPlatform/cloud-foundation-fabric pull request #1619
Opened 2023-08-23 21:11 UTC by billabongrob

#1617

2023-08-23 21:40 UTC, juliocc requested changes

2023-08-23 21:40 UTC, juliocc commented on modules/apigee/main.tf
> +  for_each    = local.instances
I think this doesn't work. You can't use `for_each` and `count` together.

Yo might want to filter `local.instances` with a comprehension.

2023-08-24 14:59 UTC, billabongrob commented
@juliocc would you mind seeing if the recent changes would meet the requirements?  I'm not sure how to trigger the actions again.

2023-08-24 17:43 UTC, juliocc approved these changes

2023-08-24 18:25 UTC, merged