Added yaml factory for custom roles and bindings
GoogleCloudPlatform/cloud-foundation-fabric pull request #1897
Opened 2023-12-02 20:15 UTC by AlexeyS-CIO

Added yaml factory:
custom roles,
iam_bindings,
iam_bindings_additive
---
**Checklist**

I applicable, I acknowledge that I have:
- [x] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [x] Ran `terraform fmt` on all modified files
- [x] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [x] Made sure all relevant tests pass

2023-12-03 14:22 UTC, ludoo requested changes
Ach, here are my comments, but then I did not actually look at the code as my objections are more of a fundamental nature.

2023-12-03 22:13 UTC, AlexeyS-CIO commented on modules/project/iam.tf
> +            description = try(data.condition.description, "")
done

2023-12-04 16:26 UTC, AlexeyS-CIO commented
Fixed, issues.
Moved factory to separated file.
If you have any questions about uses cases, we can do quick meet=)

2023-12-04 16:31 UTC, ludoo commented
Alexey, I'm not sure this fits in with the project module: if you need to manage complex roles and IAM it a) probably means the setup could be optimized (folders, etc.), and b) you manage a sizeable number of projects and should use the project factory, which already allows you to do this.

2023-12-09 07:12 UTC, ludoo commented
Alexey, I'm closing this but we added a custom roles factory for a separate change we're working on, you will see it merged  soon.

2023-12-09 07:12 UTC, closed without merging