Added variable in gke standard and autopilot modules
GoogleCloudPlatform/cloud-foundation-fabric pull request #1925
Opened 2023-12-13 10:32 UTC by luigi-bitonti

Variable `service_external_ips_config` was added to GKE Autopilot and Standard module.
---
**Checklist**

I applicable, I acknowledge that I have:
- [x] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [x] Ran `terraform fmt` on all modified files
- [x] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [x] Made sure all relevant tests pass

2023-12-13 23:10 UTC, juliocc requested changes
instead a of a new variable, can you add a new field to `var.eanble_features`?

2023-12-15 11:39 UTC, juliocc requested changes

2023-12-15 11:39 UTC, juliocc commented on modules/gke-cluster-standard/main.tf
> +  service_external_ips_config {
Make the block dynamic like (see the surrounding blocks)

2023-12-27 07:28 UTC, ludoo approved these changes

2024-01-05 16:21 UTC, juliocc commented
@luigi-bitonti I'm closing this. Feel free to reopen if you want to address the comments above

2024-01-05 16:21 UTC, closed without merging

2024-01-10 15:25 UTC, luigi-bitonti commented
> @luigi-bitonti I'm closing this. Feel free to reopen if you want to address the comments above

Hi Julio, I opened this PR with the changes you requested (dynamic block): https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/1970