IPS support for Firewall Policy
GoogleCloudPlatform/cloud-foundation-fabric pull request #2291
Opened 2024-05-20 16:17 UTC by rickygodoy

Adding `apply_security_profile_group` as **action** option and be able to provide a `security_profile_group`.
---
**Checklist**
I applicable, I acknowledge that I have:
- [X] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [X] Ran `terraform fmt` on all modified files
- [X] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [X] Made sure all relevant tests pass

2024-05-20 22:25 UTC, juliocc requested changes

2024-05-20 22:25 UTC, juliocc commented on modules/net-firewall-policy/variables.tf
> +    security_profile_group  = optional(string, null)
the null argument is redundant

2024-05-20 22:25 UTC, juliocc commented on modules/net-firewall-policy/variables.tf
> +    security_profile_group  = optional(string, null)
idem

2024-05-21 01:09 UTC, rickygodoy commented on modules/net-firewall-policy/variables.tf
> +    security_profile_group  = optional(string, null)
Fixed it, thanks so much.

2024-05-21 04:28 UTC, juliocc approved these changes

2024-05-21 04:38 UTC, merged