Kong Gateway on GKE offloading to Cloud Run
GoogleCloudPlatform/cloud-foundation-fabric pull request #2299
Opened 2024-05-21 16:04 UTC by juliodiez

Kong API Gateway on GKE with a workload running on Cloud Run.

I applicable, I acknowledge that I have:
- [x] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [x] Ran `terraform fmt` on all modified files
- [x] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [x] Made sure all relevant tests pass

2024-05-28 12:07 UTC, juliocc approved these changes

2024-05-28 12:11 UTC, juliocc requested changes

2024-05-29 14:08 UTC, juliodiez commented on blueprints/gke/patterns/kong-cloudrun/kong.tf
> +data "kubernetes_service" "admin_service" {
Done

2024-05-29 14:24 UTC, juliocc approved these changes

2024-05-29 14:26 UTC, merged