Add optional Logging and Monitoring to 3-GCVE stage
GoogleCloudPlatform/cloud-foundation-fabric pull request #2311
Opened 2024-05-27 17:37 UTC by KonradSchieban

---
**Checklist**

I applicable, I acknowledge that I have:
- [X] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [X] Ran `terraform fmt` on all modified files
- [X] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [X] Made sure all relevant tests pass

2024-05-27 22:27 UTC, juliocc requested changes
@KonradSchieban thanks for your hard work on enhancing the GCVE FAST stage! I've taken a look and have some thoughts/suggestions below

The `gcv-monitoring` module you've created doesn't fit the typical structure of a Fabric module. Fabric modules are designed to be self-contained units that manage a single, specific resource (e.g., a VM, a VPC). In contrast, your component orchestrates the creation of multiple, diverse resources: projects, subnets, service accounts, secrets, etc. 

This broader scope indicates that it functions more like a blueprint. Blueprints in Fabric are intended for higher-level orchestration of multiple components or modules to achieve a complex deployment goal.

I suggest you refactor this PR to move the `gcve-monitoring` module into the existing `pc-minimal` blueprint, or maybe its own blueprint if you think that makes sense.

Please keep in mind these points:
- Avoid direct module-to-module calls within individual modules. (calling modules is OK for blueprints). Calling modules from within blueprints is acceptable (and often necessary)
- Allow users to pass references to existing resources (e.g., subnets, service accounts) as input parameters to your blueprint. If users don't provide these references, your blueprint should automatically create the required dependencies

2024-05-27 22:27 UTC, juliocc commented on modules/gcve-monitoring/main.tf
> +data "google_compute_subnetwork" "gcve-subnetwork" {
We do not allow bare data sources, please gate it behind some sort of condition

2024-05-27 22:27 UTC, juliocc commented on modules/gcve-monitoring/main.tf
> +resource "google_compute_firewall" "healthcheck" {
what if the user's environment already provides this?

2024-05-27 22:27 UTC, juliocc commented on modules/gcve-monitoring/main.tf
> +        gcloud_secret_vsphere_password = "${local.base_gcloud_secret_manager}${var.secret_vsphere_password}"
metadata should not have sensitive data (it's visible from the UI)

2024-05-27 22:30 UTC, juliocc commented on modules/gcve-monitoring/README.md
> +module "gcve-monitoring" {
this is not showing how to use the module

2024-05-28 07:58 UTC, juliocc commented on modules/gcve-monitoring/main.tf
> +        gcloud_secret_vsphere_password = "${local.base_gcloud_secret_manager}${var.secret_vsphere_password}"
All good then :)

2024-05-28 11:18 UTC, KonradSchieban commented
> @KonradSchieban thanks for your hard work on enhancing the GCVE FAST stage! I've taken a look and have some thoughts/suggestions below
> 
> The `gcv-monitoring` module you've created doesn't fit the typical structure of a Fabric module. Fabric modules are designed to be self-contained units that manage a single, specific resource (e.g., a VM, a VPC). In contrast, your module orchestrates the creation of multiple, diverse resources: projects, subnets, service accounts, secrets, etc.
> 
> This broader scope indicates that it functions more like a blueprint. Blueprints in Fabric are intended for higher-level orchestration of multiple components or modules to achieve a complex deployment goal.
> 
> I suggest you refactor this PR to move the `gcve-monitoring` module into the existing `pc-minimal` blueprint, or into its own blueprint if you think that makes sense.
> 
> Please keep in mind these points:
> 
> * Avoid direct module-to-module calls within individual modules. Calling modules from within blueprints is acceptable (and often necessary)
> * Allow users to pass references to existing resources (e.g., subnets, service accounts) as input parameters to your blueprint. If users don't provide these references, your blueprint should automatically create the required dependencies

Thanks for your review @juliocc ! It will take some time to make this changes but I'll work on it. I'll keep this PR open in the meantime and keep you updated 👍

2024-05-29 14:38 UTC, juliocc commented
> Thanks for your review @juliocc ! It will take some time to make this changes but I'll work on it. I'll keep this PR open in the meantime and keep you updated 👍

Absolutely. Ping us if you need any help.

I'll close this in the meantime, but feel free to reopen once you're ready

2024-05-29 14:38 UTC, closed without merging