vivianvarela/cross project backend lb
GoogleCloudPlatform/cloud-foundation-fabric pull request #2453
Opened 2024-07-29 18:06 UTC by vivianvarela

---
**Checklist**

I applicable, I acknowledge that I have:
- [ ] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [ ] Ran `terraform fmt` on all modified files
- [ ] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [ ] Made sure all relevant tests pass

2024-07-29 18:26 UTC, vivianvarela reviewed
LGTM

2024-07-29 18:31 UTC, vivianvarela commented
cross project backend lb

2024-07-30 09:24 UTC, juliocc requested changes

2024-07-30 09:24 UTC, juliocc commented on modules/net-lb-app-ext-regional/README.md
> +      project_id = "backend_project_id" // Specify the project ID where the backend resides
Please use # for comments

2024-07-30 09:24 UTC, juliocc commented on modules/net-lb-app-ext-regional/README.md
> +# tftest modules=1 resources=5 e2e
remove `e2e` tag since the backend project id won't exist

2024-07-30 09:24 UTC, juliocc commented on modules/net-lb-app-ext/README.md
> +# tftest modules=1 resources=5 e2e
same comments as the other file

2024-07-30 14:11 UTC, closed without merging