add disk encyption key to the google_compute_instance_template
GoogleCloudPlatform/cloud-foundation-fabric pull request #2750
Opened 2024-12-06 13:14 UTC by rune92

---
**Checklist**

I applicable, I acknowledge that I have:
- [ ] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [ ] Ran `terraform fmt` on all modified files
- [ ] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [ ] Made sure all relevant tests pass

2024-12-06 13:41 UTC, juliocc requested changes

2024-12-06 13:41 UTC, juliocc commented on get-pip.py
remove this file

2024-12-06 13:55 UTC, juliocc commented
Thanks @rune92. This looks good now

Can you sign the CLA?

2024-12-08 09:26 UTC, ludoo commented
@rune92 can you accept our CLA?

2024-12-09 08:36 UTC, rune92 commented
> Thanks @rune92. This looks good now
> 
> Can you sign the CLA?

yepp, thanks I accepted. 

<img width="1146" alt="Screenshot 2024-12-09 at 09 36 21" src="https://github.com/user-attachments/assets/112424f4-9088-4806-9b5b-6985a9a8e1b8">

2024-12-09 08:39 UTC, ludoo commented
> > Thanks @rune92. This looks good now
> > Can you sign the CLA?
> 
> yepp, thanks I accepted.

there's one commit by `D****-K*****@t-sy****s.com` which is not passing the CLA

2024-12-09 09:23 UTC, rune92 commented
> > > Thanks @rune92. This looks good now
> > > Can you sign the CLA?
> > 
> > 
> > yepp, thanks I accepted.
> 
> there's one commit by `D****-K*****@t-sy****s.com` which is not passing the CLA

Alright, then I signed the CLA with D****-K*****@t-sy****s.com email as well. Can you check now?

2024-12-09 09:30 UTC, juliocc approved these changes

2024-12-09 09:30 UTC, merged