FAST - Fixes 498 - 02-networking-nva stage
GoogleCloudPlatform/cloud-foundation-fabric pull request #501
Opened 2022-02-04 16:09 UTC by LucaPrete

Folks, I drop here this PR before the weekend. Let's review it together carefully, as it touches important pieces.

FYI:

1. fixed GCP ASN defaults: it was conflicting with the peer ASN. Moved to 64512 as in networking-vpn
2. added a table summarizing the subnets in the readme
3. for subnets conflicts: changes spoke subnet cidr, PSA ranges and l7ILB ranges (ip subnetting [here](https://www.davidc.net/sites/default/subnets/subnets.html?network=10.128.0.0&mask=16&division=55.72755aa2ba2551)):

- the spoke subnets now consume a /20 instead of a /19
- for each spoke, the other /20 has been further subnetted, to obtain (also) 3x /24 (more below)
- the last /24 of each range is used for the corresponding regional spoke l7ilb subnet
- the second-last /24 of each range is used for PSA sql server regional spoke subnet
- the third-last /24 of each range is used for PSA mysql server regional spoke subnet

2022-02-04 16:09 UTC, LucaPrete commented
Closes #498

2022-02-04 17:17 UTC, sruffilli commented
Hey Luca, variable `custom_adv` doesn't list subnets, but aggregate ranges as they should be routed/advertised, meaning you should carve your ip space from that range.

So, using `gcp_dev_ew1="10.128.128.0/20"` as an example:

- `dev-default-ew1` subnet should be a /24
- `var.l7ilb_subnets.dev` should use the third to last available /24 for ew1 (i.e. `{ ip_cidr_range = "10.128.141.0/24", region = "europe-west1" }`)
- `var.psa_ranges.dev` should use the second to last and last available /24 for ew1 
```
    dev = {
      cloudsql-mysql-ew1     = "10.128.142.0/24"
      cloudsql-sqlserver-ew1 = "10.128.143.0/24"
#[...]
    }
```

LMK if it makes sense.

2022-02-04 17:21 UTC, sruffilli requested changes

2022-02-04 17:21 UTC, sruffilli commented on fast/stages/02-networking-nva/data/subnets/dev/dev-default-ew1.yaml
> +ip_cidr_range: 10.128.128.0/20
Per my comment, individual subnets are by default /24 carved from the IP space assigned to a specific spoke/region.

2022-02-04 17:21 UTC, sruffilli commented on fast/stages/02-networking-nva/data/subnets/dev/dev-default-ew4.yaml
> +ip_cidr_range: 10.128.160.0/20
Per my comment, individual subnets are by default /24 carved from the IP space assigned to a specific spoke/region.

2022-02-04 17:21 UTC, sruffilli commented on fast/stages/02-networking-nva/data/subnets/prod/prod-default-ew1.yaml
> +ip_cidr_range: 10.128.192.0/20
Per my comment, individual subnets are by default /24 carved from the IP space assigned to a specific spoke/region.

2022-02-04 17:21 UTC, sruffilli commented on fast/stages/02-networking-nva/data/subnets/prod/prod-default-ew4.yaml
> +ip_cidr_range: 10.128.224.0/20
Per my comment, individual subnets are by default /24 carved from the IP space assigned to a specific spoke/region.

2022-02-04 17:21 UTC, sruffilli commented on fast/stages/02-networking-nva/variables.tf
> +    gcp_dev_ew4               = "10.128.160.0/20"
I'd either use /20 or /19 everywhere

2022-02-04 17:21 UTC, sruffilli commented on fast/stages/02-networking-nva/variables.tf
> +      { ip_cidr_range = "10.128.159.0/24", region = "europe-west1" },
Per my comment, use the third to last /24 available on the carved IP estate.
Also applies to all following ranges.

2022-02-04 17:21 UTC, sruffilli commented on fast/stages/02-networking-nva/variables.tf
> +      cloudsql-mysql-ew1     = "10.128.157.0/24"
Per my comment, use the secondo to last and last /24 available on the carved IP estate.

2022-02-04 18:01 UTC, LucaPrete commented
Simo, makes sense. Good catch!

Why at this point we don’t simply advertise the whole /19 aggregate (which
is indeed dedicated to each “regional spoke”?

Il giorno ven 4 feb 2022 alle 18:18 Simone Ruffilli <
***@***.***> ha scritto:

> Hey Luca, variable custom_adv doesn't list subnets, but aggregate ranges
> as they should be routed/advertised, meaning you should carve your ip space
> from that range.
>
> So, using gcp_dev_ew1="10.128.128.0/20" as an example:
>
>    - dev-default-ew1 subnet should be a /24
>    - var.l7ilb_subnets.dev should use the third to last available /24 for
>    ew1 (i.e. { ip_cidr_range = "10.128.141.0/24", region = "europe-west1"
>    })
>    - var.psa_ranges.dev should use the second to last and last available
>    /24 for ew1
>
>     dev = {
>       cloudsql-mysql-ew1     = "10.128.142.0/24"
>       cloudsql-sqlserver-ew1 = "10.128.143.0/24"
> #[...]
>     }
>
> LMK if it makes sense.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/501#issuecomment-1030189812>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARY7UG76J4IRHUGBYX32Q3UZQC5DANCNFSM5NSFYMLQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were assigned.Message ID:
> ***@***.***
> com>
>

2022-02-05 08:19 UTC, sruffilli commented
> Simo, makes sense. Good catch! Why at this point we don’t simply advertise the whole /19 aggregate (which is indeed dedicated to each “regional spoke”?

Yep, that's the idea.

2022-02-05 11:32 UTC, LucaPrete commented
I made the changes requested.

We need to be aware that this way we'll be advertising to on-prem the l7ilb subnets as well, which won't hurt, but it's probably not what we (/users?) would like to do.

Should we use a completely different subnet for different the l7ilb subnets, so we won't announce them?

2022-02-05 15:01 UTC, sruffilli commented
I don't think you've pushed what you think you've pushed :) 
Also, please enjoy your weekend!

2022-02-07 10:52 UTC, sruffilli commented on fast/stages/02-networking-nva/README.md
> +The first /24 range is carved from each /19 and effectively allocated for the subnet.
`The first /24 range is carved from each /19 and effectively allocated for the subnet.`
->
`The first /24 on every area is allocated for a default subnet, which can be removed or modified as needed`

2022-02-07 10:52 UTC, sruffilli approved these changes

2022-02-07 10:54 UTC, sruffilli commented
LGTM modulo the required rebase and the tiny update in the README

2022-02-07 12:22 UTC, merged