Update README.md
GoogleCloudPlatform/cloud-foundation-fabric pull request #894
Opened 2022-10-17 23:42 UTC by nagendrasidgs

Added Examples to the Orgpolicies under List

2022-10-21 08:22 UTC, juliocc commented
Thanks for helping us improve our docs. Can you sign the CLA and address the comments?

Thanks!

2022-10-21 08:22 UTC, juliocc requested changes

2022-10-21 16:58 UTC, nagendrasidgs commented on blueprints/factories/project-factory/README.md
> +      values:
Thanks for the feedback. I have edited it accordingly.

2022-10-25 21:11 UTC, juliocc commented
@nagendrasidgs can you sign the CLA?

2022-10-28 16:23 UTC, nagendrasidgs commented
@juliocc  I did sign the CLA long ago. Please let me know how I can get this merged.

2022-10-28 16:28 UTC, juliocc commented
Fixed with #930

2022-10-28 16:28 UTC, closed without merging

2022-10-28 16:33 UTC, juliocc commented
@nagendrasidgs we just finished a big refactor of org policies and as a result the project factory also changed. Thew new syntax is much more readable, please take a look and let us know if you still find it unclear.